# Generated by Django 2.2.3 on 2020-01-27 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=40)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('stock_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('purchase_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
